import type { Metadata } from "next";
import { Footer, Header } from "@/components/ui";

export const metadata: Metadata = {
  title: "WDD Nerxtjs Learning 2024",
  description: "Generated by create next app",
};

export default function WebsiteLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <main>
        {children}
      </main>
      <Footer />
    </>
  );
}
